<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_account_circle  Account</name>
   <tag></tag>
   <elementGuidId>f11a7344-0fa5-458f-b7a3-380946b26819</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='navbarAccount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#navbarAccount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Show/hide account menu&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3576b2c3-4848-4285-b9ac-e4e4ea24e7a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Show/hide account menu</value>
      <webElementGuid>5d375d07-b906-474f-a26d-445c519d2a23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>navbarAccount</value>
      <webElementGuid>fd3ff751-347b-4fb0-88c9-dff11723e614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator mat-menu-trigger buttons mat-button mat-button-base cdk-focused cdk-mouse-focused</value>
      <webElementGuid>aea1a953-5640-41d1-a3d7-c5ee0e48da04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>40ff64a9-cc17-4fee-8b7f-ef683d84f973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> account_circle  Account </value>
      <webElementGuid>afdb99a3-9acd-4b5f-ac22-305ed2c33a92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarAccount&quot;)</value>
      <webElementGuid>7e80f6f4-6adb-4065-87e1-40b0b0688c5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='navbarAccount']</value>
      <webElementGuid>14b6708e-46b6-4783-9637-69f051d41a57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OWASP Juice Shop'])[4]/following::button[1]</value>
      <webElementGuid>31c8b550-43b8-43f7-8729-c2c2b400292f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='v17.1.1'])[1]/following::button[3]</value>
      <webElementGuid>6d0ef1be-87b0-44fa-a6b2-a24a9ebbed69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>7436361d-ed0c-495a-99f5-1a5efda32a8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'navbarAccount' and (text() = ' account_circle  Account ' or . = ' account_circle  Account ')]</value>
      <webElementGuid>3b150be1-d8f0-40fe-b739-1639e2571bc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
