<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Country</name>
   <tag></tag>
   <elementGuidId>ae12f3c8-abe3-4a92-9f5d-7f1dffde6e5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='address-form']/mat-form-field/div/div/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.mat-form-field-infix.ng-tns-c21-16</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Country \*$/ >> nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>37b608fa-6249-4470-9f5f-7e9a7544c978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-form-field-infix ng-tns-c21-16</value>
      <webElementGuid>505adbb7-5ecc-4593-88a6-2d56846921b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Country *</value>
      <webElementGuid>2df60fdb-d9b8-455a-9d66-c38bb6b99e44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address-form&quot;)/mat-form-field[@class=&quot;mat-form-field ng-tns-c21-16 mat-accent mat-form-field-type-mat-input mat-form-field-appearance-outline mat-form-field-can-float mat-form-field-has-label mat-form-field-hide-placeholder ng-untouched ng-pristine ng-invalid ng-star-inserted&quot;]/div[@class=&quot;mat-form-field-wrapper ng-tns-c21-16&quot;]/div[@class=&quot;mat-form-field-flex ng-tns-c21-16&quot;]/div[@class=&quot;mat-form-field-infix ng-tns-c21-16&quot;]</value>
      <webElementGuid>ada0cd18-8a8e-47d5-97d5-a6b725bb86e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='address-form']/mat-form-field/div/div/div[3]</value>
      <webElementGuid>ca50f8c2-1c4f-422a-9fec-bcbadd9839ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add New Address'])[1]/following::div[12]</value>
      <webElementGuid>e504d808-103c-40d3-a751-991321dc6c38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EN'])[1]/following::div[15]</value>
      <webElementGuid>857a6487-1b8a-4724-b9ca-8f0dbf53776d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/preceding::div[12]</value>
      <webElementGuid>b95475a8-23e7-47db-8d02-a69b5c7b7046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[3]</value>
      <webElementGuid>dc08f5ca-062f-4f72-8b8e-12ce1920925d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Country *' or . = 'Country *')]</value>
      <webElementGuid>8e1acb22-0b76-4d62-aed0-04a542e6db2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
