<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_search</name>
   <tag></tag>
   <elementGuidId>504cbb73-036a-4538-a2b3-efa7547a899f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-search-bar[@id='searchQuery']/span/mat-icon[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>mat-icon.mat-icon.notranslate.mat-ripple.mat-search_icon-search.ng-tns-c123-1.material-icons.mat-ligature-font.mat-icon-no-color</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;search&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>38c6329d-16a4-4108-bf15-a09bbda406cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c4603271-97a5-4f28-949d-715df8d0b8ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate mat-ripple mat-search_icon-search ng-tns-c123-1 material-icons mat-ligature-font mat-icon-no-color</value>
      <webElementGuid>f7e9d035-6375-4c4f-8f6e-d455516fe1c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f65b56ac-9c96-4786-bcc7-f4d93e6a08e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-type</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>20157bc1-2627-43c7-b50d-aa18d0b488f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> search </value>
      <webElementGuid>b0f9e43c-977e-42c1-9f7e-187602b70acd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchQuery&quot;)/span[@class=&quot;mat-search_icons ng-tns-c123-1&quot;]/mat-icon[@class=&quot;mat-icon notranslate mat-ripple mat-search_icon-search ng-tns-c123-1 material-icons mat-ligature-font mat-icon-no-color&quot;]</value>
      <webElementGuid>8fab7eb4-869a-497c-a570-22fba972cd79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-search-bar[@id='searchQuery']/span/mat-icon[2]</value>
      <webElementGuid>b7d7e68c-26d9-4e72-8442-63f2bb77ca3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OWASP Juice Shop'])[4]/following::mat-icon[2]</value>
      <webElementGuid>894c613c-82f2-4785-ba35-a6ef7daf1866</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='v17.1.1'])[1]/following::mat-icon[3]</value>
      <webElementGuid>7a52bf0c-1ba9-42d9-b0df-5089bb9cd9b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='account_circle'])[1]/preceding::mat-icon[1]</value>
      <webElementGuid>b669f1ba-6f5e-468b-ba88-6cda6f102ac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account'])[2]/preceding::mat-icon[1]</value>
      <webElementGuid>bbce62b7-5261-43e9-8847-5701ab72dfd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='search']/parent::*</value>
      <webElementGuid>98e08269-e85c-49f7-8cf6-b4febceae754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-icon[2]</value>
      <webElementGuid>788c81bf-bee9-4eeb-becf-e6959481cd82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-icon[(text() = ' search ' or . = ' search ')]</value>
      <webElementGuid>2f67c195-69a4-44c6-909b-fb740d254cc3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
